/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:9c504bcc-ed43-4f80-92bc-168675ad3952',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_VoMWKrPc2',
    aws_user_pools_web_client_id: '58b50jofsekqo2jko59a73u61f',
    oauth: {},
    aws_user_files_s3_bucket: 'train-me135150-prod',
    aws_user_files_s3_bucket_region: 'us-east-1',
    aws_appsync_graphqlEndpoint: 'https://vrkntbaanjdsxix2l6ipluphuy.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'AWS_IAM'
};


export default awsmobile;
